// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vjabsabpxqmfiemqwfla.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZqYWJzYWJweHFtZmllbXF3ZmxhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYxNTE3OTUsImV4cCI6MjA2MTcyNzc5NX0.i4A3qmYz1CBzIZfc1VmBsihlq_o5z3Sewi6gXXnWPqU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);