// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zpciwmwxiyrsepesuobo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpwY2l3bXd4aXlyc2VwZXN1b2JvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ1MjQyOTEsImV4cCI6MjA2MDEwMDI5MX0.956FNM__o6Eb4AWSgowHEIL4LjMasstc2Ys_aNWFovk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);